tests: Update to catch3

diff --git a/.github/workflows/pr-clazy.yml b/.github/workflows/pr-clazy.yml
--- a/.github/workflows/pr-clazy.yml
+++ b/.github/workflows/pr-clazy.yml
@@ -35,23 +35,22 @@ jobs:
           touch clazy.log
         fi
     - name: Publish Clazy Fixes
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
         name: clazy-fixes@${{ github.sha }}.yml
         path: clazy-fixes.yml
     - name: Publish Clazy Log
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
         name: clazy.log@${{ github.sha }}.yml
         path: clazy.log
     - name: Check Clazy Warnings
+      id: clazy-check
+      shell: bash
       run: |
-        if [ -e clazy.log ]; then
-          filesize=$(stat -c '%s' clazy.log)
-          if [ $filesize -gt 0 ]; then
-            echo "clazy warnings found."
-            exit 1
-          else
-            exit 0
-          fi
-        fi
+        error=$(cat clazy.log | grep -c -E "Error:|Warning:")
+        echo "::set-output name=errors-count::$errors"
+    - name: Exit if error
+      if: ${{steps.clazy-check.outputs.errors-count > 0 }}
+      shell: bash
+      run: exit 1
